config/routes.rb
Rails.application.routes.draw do

  root 'people#index'

  resources :people do
    member do
      get 'heart_rate'
      get 'ad'
      get 'spirometr'
      get 'glucometr'
      get 'weigher'
      get 'vibrotester'
      get 'audiometer'
    end
  end
  devise_for :users

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many   :people_file_cars
  validates :first_name, :second_name, :patronymic, :contact_phone,
    :mark_car, :model_car, :number_car, :last_visit, presence: true
  def full_name
    "#{first_name} #{second_name} #{patronymic}"
  end

  def full_model
    "#{mark_car} #{model_car} "
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  require 'net/http'
  require 'uri'
  require 'json'
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @q = Person.ransack(params[:q])
    @people = @q.result(distinct: true)
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @check_lists = CheckList.where(person_id: @person.id)
  end

  def ad
    if params[:systolic_bp].present?
      api_ad(params[:systolic_bp].to_i, params[:diastolic_bp].to_i, params[:complect_id].to_i)
    end
  end

  def heart_rate
    if params[:heart_rate].present?
      api_heart_rate(params[:heart_rate].to_i, params[:complect_id].to_i)
    end
  end

  def spirometr
    if params[:ofv1].present?
      api_spirometr(params[:pos_exhalation].to_f, params[:ofv1].to_f, params[:fgel].to_f, params[:complect_id].to_i)
    end
  end

  def glucometr
    if params[:glucose].present?
      api_glucometr(params[:glucose].to_f, params[:complect_id].to_i)
    end
  end

  def weigher
    if params[:weight].present?
      api_weigher(params[:weight].to_f, params[:complect_id].to_i)
    end
  end

  def vibrotester
    if params[:hr63].present?
      api_vibrotester(params)
    end
  end

  def audiometer
    if params[:ac_250_right].present?
      api_audiometer(params)
    end
  end

  def api_ad(systolic_bp, diastolic_bp, complect_id)
    if systolic_bp.present?
      body_msg     = "{\"systolic_bp\":#{systolic_bp},\"diastolic_bp\":\"#{diastolic_bp}\",\"complect_id\":#{complect_id}}"
      uri          = URI.parse("http://localhost:3000/api/ad")
      request      = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = body_msg
      response = Net::HTTP.start(uri.hostname, uri.port) do |http|
        http.request(request)
      end
      result = JSON.parse(response.body)
      redirect_to ad_person_path("test"), notice: "#{result["status"]} #{result["message"]}"
    else
      redirect_to ad_person_path("test"), notice: 'Ошибка в данных'
    end
  end

  def api_heart_rate(heart_rate, complect_id)
    if heart_rate.present?
      body_msg     = "{\"heart_rate\":#{heart_rate},\"complect_id\":#{complect_id}}"
      uri          = URI.parse("http://localhost:3000/api/heart_rate")
      request      = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = body_msg
      response = Net::HTTP.start(uri.hostname, uri.port) do |http|
        http.request(request)
      end
      result = JSON.parse(response.body)
      redirect_to heart_rate_person_path("test"), notice: "#{result["status"]} #{result["message"]}"
    else
      redirect_to heart_rate_person_path("test"), notice: 'Ошибка в данных'
    end
  end

  def api_spirometr(pos_exhalation, ofv1, fgel, complect_id)
    if pos_exhalation.present?
      body_msg     = "{\"pos_exhalation\":#{pos_exhalation},\"ofv1\":\"#{ofv1}\",\"fgel\":#{fgel},\"complect_id\":#{complect_id}}"
      uri          = URI.parse("http://localhost:3000/api/spiroment")
      request      = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = body_msg
      response = Net::HTTP.start(uri.hostname, uri.port) do |http|
        http.request(request)
      end
      result = JSON.parse(response.body)
      redirect_to spirometr_person_path("test"), notice: "#{result["status"]} #{result["message"]}"
    else
      redirect_to spirometr_person_path("test"), notice: 'Ошибка в данных'
    end
  end

  def api_glucometr(glucose, complect_id)
    if glucose.present?
      body_msg     = "{\"glucose\":#{glucose},\"complect_id\":#{complect_id}}"
      uri          = URI.parse("http://localhost:3000/api/blood_glucose_meter")
      request      = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = body_msg
      response = Net::HTTP.start(uri.hostname, uri.port) do |http|
        http.request(request)
      end
      result = JSON.parse(response.body)
      redirect_to glucometr_person_path("test"), notice: "#{result["status"]} #{result["message"]}"
    else
      redirect_to glucometr_person_path("test"), notice: 'Ошибка в данных'
    end
  end

  def api_weigher(weight, complect_id)
    if weight.present?
      body_msg     = "{\"weight\":#{weight},\"complect_id\":#{complect_id}}"
      uri          = URI.parse("http://localhost:3000/api/weigher")
      request      = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = body_msg
      response = Net::HTTP.start(uri.hostname, uri.port) do |http|
        http.request(request)
      end
      result = JSON.parse(response.body)
      redirect_to weigher_person_path("test"), notice: "#{result["status"]} #{result["message"]}"
    else
      redirect_to weigher_person_path("test"), notice: 'Ошибка в данных'
    end
  end

  def api_vibrotester(params)
    if params[:hr63].present?
      body_msg     = "{\"hr63\":#{params[:hr63]},\"hr125\":#{params[:hr125]},\"hr250\":#{params[:hr250]},\"hl63\":#{params[:hl63]},\"hl125\":#{params[:hl125]},\"hl250\":#{params[:hl250]},\"fr125\":#{params[:fr125]},\"fl125\":#{params[:fl125]},\"complect_id\":#{params[:complect_id]}}"
      uri          = URI.parse("http://localhost:3000/api/vibrotester")
      request      = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = body_msg
      response = Net::HTTP.start(uri.hostname, uri.port) do |http|
        http.request(request)
      end
      result = JSON.parse(response.body)
      redirect_to vibrotester_person_path("test"), notice: "#{result["status"]} #{result["message"]}"
    else
      redirect_to vibrotester_person_path("test"), notice: 'Ошибка в данных'
    end
  end

  def api_audiometer(params)
    if params[:ac_250_right].present?
      body_msg     = "{\"ac_250_right\":#{params[:ac_250_right]},\"ac_500_right\":#{params[:ac_500_right]},\"ac_1000_right\":#{params[:ac_1000_right]},\"ac_2000_right\":#{params[:ac_2000_right]},\"ac_4000_right\":#{params[:ac_4000_right]},\"ac_250_left\":#{params[:ac_250_left]},\"ac_500_left\":#{params[:ac_500_left]},\"ac_1000_left\":#{params[:ac_1000_left]},\"ac_2000_left\":#{params[:ac_2000_left]},\"ac_4000_left\":#{params[:ac_4000_left]},\"complect_id\":#{params[:complect_id]}}"
      uri          = URI.parse("http://localhost:3000/api/audiometer")
      request      = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
      request.body = body_msg
      response = Net::HTTP.start(uri.hostname, uri.port) do |http|
        http.request(request)
      end
      result = JSON.parse(response.body)
      redirect_to audiometer_person_path("test"), notice: "#{result["status"]} #{result["message"]}"
    else
      redirect_to audiometer_person_path("test"), notice: 'Ошибка в данных'
    end
  end
  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Клиент создан' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Данные клиента обновлены.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Клиент удален из базы.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :second_name, :patronymic, :sex, :contact_phone,
        :mark_car, :model_car, :number_car, :last_visit, :description, :comment)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
= simple_form_for @person, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-4
        .form-group
          = f.input :mark_car
      .col-md-4
        .form-group
          = f.input :model_car
      .col-md-4
        .form-group
          = f.input :number_car
    .row
      .col-md-4
        .form-group
          = datepicker_field(f, :last_visit)
      .col-md-4
        .form-group
          = f.input :contact_phone
      .col-md-4
        .form-group
          = f.input :description

    .row
      .col-md-4
        .form-group
          = f.input :first_name
      .col-md-4
        .form-group
          = f.input :second_name
      .col-md-4
        .form-group
          = f.input :patronymic

  %br/

  .form-actions
    = link_to "Назад", Person,  class: 'btn btn-primary'
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/people/ad.html.haml
.page-header.text-center
  %h1= "АД"
= simple_form_for '', method: :get, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-12
        .form-group
          = f.input :systolic_bp, label: "САД", placeholder: "Формат:  99", value: params[:systolic_bp]
    .row
      .col-md-12
        .form-group
          = f.input :diastolic_bp, label: "ДАД", placeholder: "Формат:  99", value: params[:diastolic_bp]
    .row
      .col-md-12
        .form-group
          = f.input :complect_id, label: "Прибор", value: params[:complect_id]
  .inline
    = submit_tag 'Отправить данные', class: 'btn btn-primary'
    = link_to 'Назад',  people_path, class: 'btn btn-default'

app/views/people/audiometer.html.haml
.page-header.text-center
  %h1= "Аудиометр"
= simple_form_for '', method: :get, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-12
        .form-group
          = f.input :ac_250_right, label: "Воздушная проводимость 250 Справа", placeholder: "Формат:  99", value: params[:ac_250_right]
    .row
      .col-md-12
        .form-group
          = f.input :ac_500_right, label: "Воздушная проводимость 500 Справа", placeholder: "Формат:  99", value: params[:ac_500_right]
    .row
      .col-md-12
        .form-group
          = f.input :ac_1000_right, label: "Воздушная проводимость 1000 Справа", placeholder: "Формат:  99", value: params[:ac_1000_right]
    .row
      .col-md-12
        .form-group
          = f.input :ac_2000_right, label: "Воздушная проводимость 2000 Справа", placeholder: "Формат:  99", value: params[:ac_2000_right]
    .row
      .col-md-12
        .form-group
          = f.input :ac_4000_right, label: "Воздушная проводимость 4000 Справа", placeholder: "Формат:  99", value: params[:ac_4000_right]
    .row
      .col-md-12
        .form-group
          = f.input :ac_250_left, label: "Воздушная проводимость 250 Слева", placeholder: "Формат:  99", value: params[:ac_250_left]
    .row
      .col-md-12
        .form-group
          = f.input :ac_500_left, label: "Воздушная проводимость 500 Слева", placeholder: "Формат:  99", value: params[:ac_500_left]
    .row
      .col-md-12
        .form-group
          = f.input :ac_1000_left, label: "Воздушная проводимость 1000 Слева", placeholder: "Формат:  99", value: params[:ac_1000_left]
    .row
      .col-md-12
        .form-group
          = f.input :ac_2000_left, label: "Воздушная проводимость 2000 Слева", placeholder: "Формат:  99", value: params[:ac_2000_left]
    .row
      .col-md-12
        .form-group
          = f.input :ac_4000_left, label: "Воздушная проводимость 4000 Слева", placeholder: "Формат:  99", value: params[:ac_4000_left]

    .row
      .col-md-12
        .form-group
          = f.input :complect_id, label: "Прибор", value: params[:complect_id]
  .inline
    = submit_tag 'Отправить данные', class: 'btn btn-primary'
    = link_to 'Назад',  people_path, class: 'btn btn-default'

app/views/people/edit.html.haml
.page-header
  %h1= t('headers.people.edit')

= render 'form'

app/views/people/glucometr.html.haml
.page-header.text-center
  %h1= "Глюкометр"
= simple_form_for '', method: :get, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-12
        .form-group
          = f.input :glucose, label: "Глюкоза крови", placeholder: "Формат:  99.9", value: params[:glucose]
    .row
      .col-md-12
        .form-group
          = f.input :complect_id, label: "Прибор", value: params[:complect_id]
  .inline
    = submit_tag 'Отправить данные', class: 'btn btn-primary'
    = link_to 'Назад',  people_path, class: 'btn btn-default'

app/views/people/heart_rate.html.haml
.page-header.text-center
  %h1= "ЧСС"
= simple_form_for '', method: :get, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-12
        .form-group
          = f.input :heart_rate, label: "ЧСС", placeholder: "Формат:  99", value: params[:heart_rate]
    .row
      .col-md-12
        .form-group
          = f.input :complect_id, label: "Прибор", value: params[:complect_id]
  .inline
    = submit_tag 'Отправить данные', class: 'btn btn-primary'
    = link_to 'Назад',  people_path, class: 'btn btn-default'

app/views/people/index.html.haml
.page-header.text-center
  %h1= t('headers.people.index')

%nav{class: 'menu'}
  = link_to ad_person_path("test"), class: 'btn btn-success' do
    = fa_icon :check
    = "Тонометр (АД)"

  = link_to heart_rate_person_path("test"), class: 'btn btn-success' do
    = fa_icon :check
    = "Тонометр (ЧСС)"

  = link_to spirometr_person_path("test"), class: 'btn btn-success' do
    = fa_icon :check
    = "Спирометр"

  = link_to glucometr_person_path("test"), class: 'btn btn-success' do
    = fa_icon :check
    = "Глюкометр"

  = link_to weigher_person_path("test"), class: 'btn btn-success' do
    = fa_icon :check
    = "Весы"

  = link_to vibrotester_person_path("test"), class: 'btn btn-success' do
    = fa_icon :check
    = "Вибротестер"

  = link_to audiometer_person_path("test"), class: 'btn btn-success' do
    = fa_icon :check
    = "Аудиометр"

-# %table.table.table-hover
-#   %caption
-#     = link_to spirometr_person_path("test"), class: 'btn btn-success' do
-#       = fa_icon :check
-#       = "Спирометр"
-#     %br
-#     %br
-#     = link_to glucometr_person_path("test"), class: 'btn btn-success' do
-#       = fa_icon :check
-#       = "Глюкометр"
-#     %br
-#     %br
-#     = link_to weigher_person_path("test"), class: 'btn btn-success' do
-#       = fa_icon :check
-#       = "Весы"

app/views/people/new.html.haml
.page-header
  %h1= t('headers.people.new')

= render 'form'

app/views/people/show.html.haml
.page-header
  %h1= "#{@person.full_name}"
= link_to 'Добавить файлы', new_file_car_path(), class: 'btn btn-success'
= link_to 'Оформить заказ наряд', new_check_list_path(person_id: params[:id]), class: 'btn btn-success'
%br/
%br/
%dl
  .well.col-md-12
    .row
      .col-md-2
        %dt= Person.human_attribute_name(:mark_model)
        %dd= @person.full_model
      .col-md-2
        %dt= Person.human_attribute_name(:number_car)
        %dd= @person.number_car
      .col-md-2
        %dt= Person.human_attribute_name(:last_visit)
        %dd= l @person.last_visit, format: :default
    .row
      .col-md-2
        %dt= Person.human_attribute_name(:contact_phone)
        %dd= @person.contact_phone
      .col-md-2
        %dt= Person.human_attribute_name(:fio)
        %dd= @person.full_name
      .col-md-2
        %dt= Person.human_attribute_name(:description)
        %dd= @person.description
    .row
      .col-md-6
        %dt= Person.human_attribute_name(:files)
        - @person.people_file_cars.each do |f|
          - f.file_car.avatars.each do |file|
            %dd= link_to "#{file.file.filename}", file.url ,target: '_blank'
      .col-md-4
        %dt= Person.human_attribute_name(:files_date)
        - @person.people_file_cars.each do |f|
          - f.file_car.avatars.each do |file|
            %dd= l f.file_car.created_at, format: :long
%br
%br
%table.table.table-hover.sortable
  %thead
    %tr
      %th= CheckList.human_attribute_name(:admin_id)
      %th= CheckList.human_attribute_name(:services)
      %th= CheckList.human_attribute_name(:total_price)
      %th= CheckList.human_attribute_name(:order_date)



  %tbody
    - @check_lists.each do |check_list|
      %tr
        %td= check_list.admin.present? ? (check_list.admin.full_name ) : "отсутствует"
        %td
          - check_list.orders.each do |o|
            %dd= o.name_service + " #{o.price} " + "руб."
        %td= "#{check_list.price} руб."
        %td= check_list.order_date.present? ? (l check_list.order_date, format: :default) : "отсутствует"


.text-center
  %br/
  %br/
  = link_to 'К кспику клиентов', people_path, class: 'btn btn-primary btn-sm'
  = link_to 'Изменить', edit_person_path(@person), class: 'btn btn-primary btn-sm'

app/views/people/spirometr.html.haml
.page-header.text-center
  %h1= "Спирометр"
= simple_form_for '', method: :get, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-12
        .form-group
          = f.input :pos_exhalation, label: "ПОС", placeholder: "Формат:  99.99", value: params[:pos_exhalation]
    .row
      .col-md-12
        .form-group
          = f.input :ofv1, label: "ОФВ1", placeholder: "Формат:  99.99", value: params[:ofv1]
    .row
      .col-md-12
        .form-group
          = f.input :fgel, label: "ФЖЕЛ", placeholder: "Формат:  99.99", value: params[:fgel]
    .row
      .col-md-12
        .form-group
          = f.input :complect_id, label: "Прибор", value: params[:complect_id]
  .inline
    = submit_tag 'Отправить данные', class: 'btn btn-primary'
    = link_to 'Назад',  people_path, class: 'btn btn-default'

app/views/people/vibrotester.html.haml
.page-header.text-center
  %h1= "Вибротестер"
= simple_form_for '', method: :get, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-12
        .form-group
          = f.input :hr63, label: "Вч 63 Кисть справа", placeholder: "Формат:  99.9", value:  params[:hr63]
    .row
      .col-md-12
        .form-group
          = f.input :hr125, label: "Вч 125 Кисть справа", placeholder: "Формат:  99.9", value: params[:hr125]
    .row
      .col-md-12
        .form-group
          = f.input :hr250, label: "Вч 250 Кисть справа", placeholder: "Формат:  99.9", value: params[:hr250]
    .row
      .col-md-12
        .form-group
          = f.input :hl63, label: "Вч 63 Кисть слева", placeholder: "Формат:  99.9", value:  params[:hl63]
    .row
      .col-md-12
        .form-group
          = f.input :hl125, label: "Вч 125 Кисть слева", placeholder: "Формат:  99.9", value: params[:hl125]
    .row
      .col-md-12
        .form-group
          = f.input :hl250, label: "Вч 250 Кисть слева", placeholder: "Формат:  99.9", value: params[:hl250]
    .row
      .col-md-12
        .form-group
          = f.input :fr125, label: "Вч 125 Стопа справа", placeholder: "Формат:  99.9", value: params[:fr125]
    .row
      .col-md-12
        .form-group
          = f.input :fl125, label: "Вч 125 Стопа слева", placeholder: "Формат:  99.9", value: params[:fl125]

    .row
      .col-md-12
        .form-group
          = f.input :complect_id, label: "Прибор", value: params[:complect_id]
  .inline
    = submit_tag 'Отправить данные', class: 'btn btn-primary'
    = link_to 'Назад',  people_path, class: 'btn btn-default'

app/views/people/weigher.html.haml
.page-header.text-center
  %h1= "Весы"
= simple_form_for '', method: :get, html: { class: 'col-md-6 col-md-offset-3 text-center', role: 'form1' } do |f|
  .well
    .row
      .col-md-12
        .form-group
          = f.input :weight, label: "Вес", placeholder: "Формат:  999.99", value: params[:weight]
    .row
      .col-md-12
        .form-group
          = f.input :complect_id, label: "Прибор", value: params[:complect_id]
  .inline
    = submit_tag 'Отправить данные', class: 'btn btn-primary'
    = link_to 'Назад',  people_path, class: 'btn btn-default'